[workspace]
members = [
    "backend",
    "dead_x_sniper", "one_time_x_snipe",
    "say_gm",
    "shared",
    "soft_shills_manager",
]
resolver = "2"

[profile.release]
strip = true        # Remove symbols from binary
opt-level = 3       # Maximum optimization for speed
lto = true          # Optimize at link stage ("fat")
codegen-units = 1   # Reduce parallel codegen to maximize optimizations
panic = "abort"     # Remove unwind information, reducing binary size and overhead (no backtraces in production)
