[package]
name = "say_gm"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
shared = {path = "../shared"}
grammers-client = "0.7.0"
grammers-session = "0.7.0"
dotenv = "0.15.0"