name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dynnax
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Setup .env files
      run: |
        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/dynnax" >> ./backend/.env

    - name: Install sqlx CLI
      run: cargo install sqlx-cli

    - name: Run tests
      working-directory: ./backend
      run: cargo test -- --nocapture

    - name: Build release
      working-directory: ./backend
      run: cargo build --release
